### ISSUE TITLE
Camera locks up

### ISSUE THREAD

**Issue by GoogleCodeExporter** [400plus/400plus#338]
```
What steps will reproduce the problem?
Camera locks up randomly.

What is the expected output? What do you see instead?
First the display seems frozen, and buttons stop responding; after taking a 
shot, camera becomes completely unresponsive, and must remove batteries to 
switch it off.

What version of the product are you using?
20130414-02

Please provide any additional information below.

```

Original issue reported on code.google.com by `eduardo....@gmail.com` on 30 May 2013 at 10:06

**Comment by eduperez** [comment]
Please try latest BETA release at https://github.com/400plus/400plus/releases/tag/20150422-BETA; I hope all these problems have been finally solved.

**Comment by eduperez** [comment]
After disabling the display overlay, I have made thousands of shots and experienced no lock-up at all.
