### ISSUE TITLE
Migrating to GitHub

### ISSUE THREAD

**Issue by GoogleCodeExporter** [400plus/400plus#354]
```
Hi !

Google Code will be closing its doors soon (by august 2015, our repository will 
be read-only). I suggest using GitHub instead, which is a nice replacement to 
Google Code. We can even integrate it with some CI software such as Travis.
```

Original issue reported on code.google.com by `tiboun...@gmail.com` on 13 Mar 2015 at 7:06

**Comment by tibounise** [comment]
I've added a `.gitignore` file in commit [78f9aa1257](https://github.com/400plus/400plus/commit/78f9aa1257fddc822560a2dd6386f77b5487bfed) so we won't push by accident build files into the repository.

**Comment by eduperez** [comment]
Our site at Google Code is closed, and there is just a pointer to GitHUB there; work is finished.
