### ISSUE TITLE
My translation to german

### ISSUE THREAD

**Issue by Popcorn13** [400plus/400plus#366]
Hello everybody
I'm a new user and I love 400plus :+1: 

I wrote a new translation for german users and I would like to share it with all users.
But how can I upload german.ini as it is written in the translation guide? Is it an old description for google code?

**Comment by eduperez** [comment]
Oh, yes! The translation guide was written when 400plus was hosted at Google Code, and we could upload files in the issues; nobody noticed that GitHub does not allow that, and we have not updated the wiki. I'm sorry about that.

Just upload the file somewhere, and post the URL here, please.

**Comment by 0xAF** [comment]
Or make a pull request, if you know how to do it.

**Comment by Popcorn13** [comment]
https://www.dropbox.com/s/ht0kf1g7iz7e8sq/german.ini?dl=0

**Comment by eduperez** [comment]
Released as 20130414-06; many thanks.
