### ISSUE TITLE
Wrong render with Chinese character in the menu item

### ISSUE THREAD

**Issue by neo954** [400plus/400plus#367]
Enclosed please find a screen shot. Well, it is not a real screen shot. I just take a photo with my cell phone against the screen of the EOS 400D camera.

As you can see from the screen shot, I tried to do a Simplified Chinese translation for 400plus. As soon as I began the work, I noticed there are two problem.

The first one, not all Chinese characters are available in the Canon Firmware. I think Canon intend to save storage space in this way. There are thousands of characters. I think Canon just included those characters are being used in the menu in the firmware. If I use some characters which are not included in the firmware, things just messed up. The entire menu went to blank. For this issue, I think the best workaround method is making the translate file carefully, and use only those existing characters.

The second issue, is Chinese character is wider then English character. From the screen shot, English character is around 16x8 dot matrix, and Chinese character is around 19x15 dot matrix. And as you can see in the screen shot, the Right Angle Bracket character in the menu is mis-aligned. I do not have good idea for this issue.

![400plus 00](https://cloud.githubusercontent.com/assets/12424088/7813656/55ed0434-03ef-11e5-82f4-6eed47c4671a.jpg)

**Comment by neo954** [comment]
The file simplified_chinese.ini I used for testing. Most of the items are untouched, in order to avoid mess things up.

[SIMPLIFIED_CHINESE]
A_FLASH                = Flash
A_MIRROR_LOCKUP        = 反光镜预升
A_NO                   = 关
A_YES                  = 开
I_ACTION               = Action
I_AEB                  = AEB
I_AF_FLASH             = AF Flash
I_APPLY                = Apply
I_ASSIGN               = Assign
I_AUTOISO_ENABLE       = 启动
I_AUTOISO_MAXAV        = Max Av
I_AUTOISO_MAXISO       = Max ISO
I_AUTOISO_MINISO       = Min ISO
I_AUTOISO_MINTV        = Min Tv
I_AUTOISO_RELAX        = Relaxed
I_AUTOSAVE             = Autosave
I_AV_COMP              = AV comp.
I_AV_VAL               = Av
I_BODY_ID              = Body ID
I_BTN_JUMP             = Jump
I_BTN_TRASH            = Trash
I_BUTTON_DISP          = Better DISP button
I_CMODES_400PLUS       = 400plus
I_CMODES_CAMERA        = Camera
I_CMODES_CFN           = Custom Fn
I_CMODES_IMAGE         = Image
I_CMODES_ORDERING      = Menu order
I_CMODES_SETTINGS      = Settings
I_COLOR_TEMP_K         = Color temp. (K)
I_DEBUG_ON_POWERON     = Debug on PowerOn
I_DELAY                = 2s Delay
I_DELETE               = Delete
I_DELETE_CMODES        = Delete custom modes
I_DEVELOPERS_MENU      = Developers' menu
I_DIG_ISO_STEP         = Digital ISO step
I_DIRECTION            = Direction
I_DOFMAX               = Max. DOF (m)
I_DOFMIN               = Min. DOF (m)
I_DUMP_LOG_TO_FILE     = Dump log to file
I_DUMP_MEMORY          = Dump RAM after 5s
I_EAEB                 = EAEB
I_ENTER_FACTORY_MODE   = Enter factory Mode
I_ENTER_MAIN           = Enter to main
I_EV_VAL               = Ev
I_EXIT_FACTORY_MODE    = Exit  factory Mode
I_EXPOSURE             = Exposure
I_FDIST                = Focus distance (m)
I_FIRMWARE             = 固件
I_FLASH_2ND_CURT       = 闪光第二帘幕
I_FLASH_COMP           = Flash comp.
I_FLENGTH              = Focal length (mm)
I_FRAMES               = Frames
I_INDICATOR            = Indicator
I_INSTANT              = Instant
I_INTERVAL             = Interval
I_INVERT_OLC           = Change OLC Colors
I_IR_REMOTE_DELAY      = IR remote delay
I_IR_REMOTE_ENABLE     = IR remote enable
I_ISO                  = ISO
I_KEEP_POWER_ON        = 关闭 power-off
I_LANGUAGE             = Language
I_LCD_SCRIPT           = LCD display
I_LOGFILE_MODE         = Log File Mode
I_MANUAL_L             = Bulb min
I_MANUAL_R             = Bulb max
I_MEMSPY_DISABLE       = MemSpy 关闭
I_MEMSPY_ENABLE        = MemSpy 启动
I_MIRROR_LOCKUP        = Mirror Lockup
I_NAVIGATE_MAIN        = Navigate to main
I_OWNER                = Owner
I_PERSIST_AEB          = Persist AEB
I_PLAYTIME             = Playback time
I_PRINT_INFO           = Print info to log
I_QEXP_MINTV           = Min Tv
I_QEXP_WEIGTH          = Weight
I_RAMPING_EXP          = Ramping (exposure)
I_RAMPING_TIME         = Ramping (interval)
I_RAMP_S               = Ramp size (shots)
I_RAMP_T               = Ramp size (time)
I_RECTIME              = Recording time
I_RELEASE_COUNT        = Release count
I_RENAME               = Rename
I_REPEAT               = Repeat
I_RESTORE              = Restore config.
I_RESTORE_CMODES       = Restore custom modes
I_RESTORE_SETTINGS     = Restore settings
I_REVIEW_OFF           = 关闭 review
I_SAFETY_SHIFT         = Safety Shift
I_SAVE                 = Save
I_SHOTS                = Shots
I_STEP_EV              = Step (EV)
I_TEST_DIALOGS         = Test dialogs
I_TIME                 = Time (s)
I_TV_VAL               = Tv
I_UNASSIGN             = Unassign
I_UPDATE               = Update
I_USE_DPAD             = Use D-Pad
I_USE_FLASH            = 关闭 flash
I_VERSION              = Version
I_VFORMAT              = Video format (fps)
I_WRAP_MENUS           = Menus wrap
P_400PLUS              = 400plus
P_CMODES               = Custom modes
P_DEVELOPERS           = Developers' Menu
P_INFO                 = Info
P_PARAMS               = Parameters
P_RENAME               = Rename
P_SCRIPTS              = Scripts
P_SETTINGS             = Settings
S_APT_AEB              = Aperture AEB
S_AUTOISO              = AutoISO
S_BRAMP                = Bulb ramping
S_BUTTONS              = 配置 Buttons
S_CALCULATOR           = Calculator
S_CMODES               = 配置 Custom modes
S_CMODE_NAME           = Custom mode
S_DOF_CALC             = DOF Calculator
S_EFL_AEB              = Flash AEB
S_EXT_AEB              = Extended AEB
S_FLASH                = Flash
S_HANDWAVE             = Handwaving
S_INFINITE             = INF!
S_INTERVAL             = Intervalometer
S_IR                   = Infrared Remote
S_ISO_AEB              = ISO AEB
S_LEXP                 = Long exposures
S_MENUS                = 配置 Menus
S_NAMED_TEMPS          = Named color temps.
S_PAGES                = 配置 Pages
S_QEXP                 = 配置 Quick exposure
S_SCRIPTS              = 配置 Scripts
S_TIMER                = Self-Timer
V_APPEND               = Append
V_APT_AEB              = Apt. AEB
V_AV                   = Av
V_BOTH                 = Both
V_CAMERA               = Camera
V_DIM                  = Dim down
V_DISABLED             = 关闭
V_EFL_AEB              = Flash AEB
V_ENABLED              = 启动
V_EXT_AEB              = Ext. AEB
V_EXT_ONLY             = Ext Only
V_FAST                 = Fast
V_HACK_MENU            = 400Plus Main Menu
V_INTISO               = Intermediate ISO
V_ISO_AEB              = ISO AEB
V_KEEP                 = Keep
V_LEXP                 = Long exp.
V_MEDIUM               = Medium
V_NAMED_TEMP_0         = Match flame
V_NAMED_TEMP_1         = Candle flame
V_NAMED_TEMP_2         = Tungsten light
V_NAMED_TEMP_3         = Fl. Warm White
V_NAMED_TEMP_4         = Fl. White
V_NAMED_TEMP_5         = Fl. Cool White
V_NAMED_TEMP_6         = Fl. Daylight
V_NAMED_TEMP_7         = Daylight
V_NAMED_TEMP_8         = Sunny
V_NAMED_TEMP_9         = Flash
V_NAMED_TEMP_A         = Cloudy
V_NAMED_TEMP_B         = Shade
V_NAMED_TEMP_C         = D50
V_NAMED_TEMP_D         = D55
V_NAMED_TEMP_E         = D65
V_NAMED_TEMP_F         = D75
V_NEW                  = New
V_NO                   = No
V_NONE                 = None
V_NO_LIMIT             = No Limit
V_OFF                  = Off
V_ONE_SHOT             = One Shot
V_OVERWRITE            = Overwrite
V_REPEAT               = Repeat last script
V_SLOW                 = Slow
V_TOGGLE_FLASH         = Flash on/off
V_TV                   = Tv
V_YES                  = Yes

**Comment by eduperez** [comment]
I also think that Canon only included those characters from the Chinese language that they needed in the original menus. And when an unknown character is used, the menu just stops printing any character until the end of the line.

Perhaps we could try to create our own font and add to 400plus, but that means we will have to rewrite all the menu displaying routines also, and I am not sure that we can fit the entire Chinese alphabet into the camera's memory. I am afraid this does not seem like a viable solution to me, and we will have to deal with only the included characters.

The ">" symbol is placed counting characters and using spaces, I guess we could count double for Chinese characters, but I am not sure that we will really be able put it in the exact place.

At the end, it looks like we will only have a few Chinese strings, and the ">" will be badly placed anyway...

**Comment by 0xAF** [comment]
Putting our font in 400Plus is not a good option, at least, not without spending huge amount of time to implement a screen drawing routines (and suspending the real menu system) and implement a new menu system/structure over this new API. Or perhaps steal a bit from ML... anyway, it will take considerable amount of time.

**Comment by neo954** [comment]
I think counting characters is not good solution. Since each Chinese character is not exact double width as an English character. Maybe we should use the style which Canon origianl menu used. Use a second column for the current value of each menu item and use left align. In this way, we can avoid counting characters.

In that way, I think I can work out a proper Chinese translation, with only the existing/available Chinese characters.

I belive the same thing happenned for Japanese language and Korean laguage. We neeed a general solution for all the east asia languages.

**Comment by 0xAF** [comment]
That wont be easy too, because the menu structure we are using is one column only (the while line). We cannot easily change each different line to achieve the 2 columns for some of the lines (even for all of the lines), but I could be mistaken here.

**Comment by eduperez** [comment]
I agree with 0xAF.
