### ISSUE TITLE
wiki_Installation guide EOScard wrong?

### ISSUE THREAD

**Issue by Popcorn13** [400plus/400plus#373]
Hey all

tried all methods to make CF card bootable. (WIN7)
Only this one worked for me:

1. format card using camera (or PC)
2. copy autoexec.bat & language.ini from latest release to CF card
3. start EOScard V1.4 (no admin-mode etc.) & click "refresh"
4. Check EOS_DEVELOP and BOOTDISK & click "save"
- no ML files are copied, nothing to remove.
5. have fun with 400plus

Please check and update installation guide.

Regards
Andy / Popcorn13

**Comment by eduperez** [comment]
The wiki page has been updated; many thanks!
