### ISSUE TITLE
Improve "smart DISP" feature

### ISSUE THREAD

**Issue by eduperez** [400plus/400plus#381]
It would be useful to know what brightness value we are setting. We could use the "remaining shots on card" value, or use a combination of DISP+WHEEL, or...

**Comment by Eldurinn** [comment]
That sounds like a great idea. Right now I'm counting up to 7 (or whatever brightness value when I'm changing it) and if I go to far, I have to start over.

**Comment by eduperez** [comment]
Fixed with 7baea9eb953966db3eabf19be2c549a69b3c5200.
