### ISSUE TITLE
C.Fn 01 = "4:Cross keys: AF frame selec." causes some issues

### ISSUE THREAD

**Issue by KicknGuitar** [400plus/400plus#411]
For the longest time I've been using the firmware, the AF-Pattern Selection never played well.

When in the selection (pressing Zoom-In once):
- It won't exit unless pressing the Menu, Preview, or Drive (Shooting mode) button.
- The Zoom-in button won't reset the AF-pattern to all points until Zoom-_out_ is pressed.
- Using the shortcuts after the AF-pattern selection] sometimes close AF selection, but other times won't (and still display the shortcut name)

This is an issue when trying to adjust the focus point, then ISO, spot metering, or the other functions on the arrow buttons.

One idea about it: An option to disable  the zoom-in button's flash-test and repurpose it work as the close button

**Comment by eduperez** [comment]
Sorry, but I am not sure I am understanding the issue here...

- When you press the zoom-in button just once, you enter the native AF-Point selection dialog; 400plus does not interfere here, unless you press the zoom-in button again. So, you are proposing an enhancement to the native AF-Point selection dialog? Or are you complaining about the extended AF-Pattern selection dialog?
- In my machine, both the native AF-Point and the extended AF-Pattern selection dialogs exit when I half-press the shutter button, or the zoom-out button. Which other buttons should exit the AF dialogs?
- Why should the zoom-in button reset the AF-Pattern to all points? That is not how the native AF-Point selection dialog works.
- I could not reproduce the issue with the shortcuts; can you find a sequence of buttons that fails, please?

**Comment by KicknGuitar** [comment]
Maybe I'm forgetting how the buttons work. Or maybe It's been a bad hack install in the camera's firmware since I did this years ago. This has been the case for quite a while.

In the event it's not me (although I'm beginning to believe it's on my end), when I follow what works for you:

- Zoom-in button does nothing. Even when double pressed.
- The Zoom-in will only select all AF points _after_ pressing the zoom-out button.
- The Zoom-out does enter me into the AF-pattern selection (nothing occurs on the display but through the viewfinder I can see the star icon)
- After pressing Zoom-out I can only use the D-pad for AF until I press the Menu/Preview/ShootingMode buttons.
- Pressing the shutter half-way does not close the AF selector.
Some extra bits:
- Zoom-in selects all focus points (when in the AF selector)

I'm on ver-20160404-01
Firmware 1.1.1

**Comment by eduperez** [comment]
20160404-01 is the latest release, the same I am using here; and once the camera has been prepared, it should work exactly the same on all cameras. So I think that there is something strange going on here.

I'll prepare a video tonight, showing how it works in my camera, and we can compare with yours.

**Comment by eduperez** [comment]
Here we go: https://youtu.be/XEXrrHtYz1M

**Comment by KicknGuitar** [comment]
Well, this is odd. It happens across all four of my cards. With or without the settings.
And more shocking is, I totally forgot about that new window in the display. I _never_ see that. But it looks very familiar. I wonder if I lost it a while back. I think this is all on my end. That's good and bad :/

**Comment by eduperez** [comment]
Could you please try with 400plus disabled (just start the camera with no CF card inserted)? I am curious to see whether it is something produced by 400plus, or the original firmware.

**Comment by KicknGuitar** [comment]
HAHA, Oh my. This is what happens when you have so many options and you rarely change them. Truely sorry about that.

But now you know that this custom function will interfere with using 400plus' custom buttons, until the user exits it with the menu, preview, or shooting mode buttons.

**Comment by eduperez** [comment]
I am not seeing any event at the usual places (intercom): there is nothing when the camera enters this mode, and there is nothing when the users presses the cursor buttons... So we are basically blind, and cannot detect when the camera enters this state (to disable the shortcuts) or when the user presses any button (to enable the AF-pattern selection).

**Comment by eduperez** [comment]
First and second points are normal behavior when C.Fn 01 is set to 4.
Change mentioned above disables shortcuts when  C.Fn 01 is set to 4.
