### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by Wizhunter** [400plus/400plus#416]
I have tried all the methods to get 400 plus to work. I am running Windows 10 and trying to add 400 plus to a 16 gb CF card. When I tried with postcard it won't let me tick both boxes. Tried had also, I do everything to the letter and still no joy. I am not a professional user of a pc but can do things if they are easy to understand. Please help I would love to use 400 plus.

Thanks in advance
Wizhunter

**Comment by Wizhunter** [comment]
Forgot to say that I have no problem doing the first part with the testify file, it's just the part incorporating the autoexec bin file that I can't get working.

**Comment by eduperez** [comment]
Well, the formatting part is usually where most people finds difficulties. Once the card has been formatted, just open it with the file explorer in Windows, delete all the files that EOSCard might have left there, and copy there the AUTOEXEC.BIN file you downloaded.

I'll try to make a video with the procedure, if I can find a Windows box to play with.

**Comment by Wizhunter** [comment]
I tried that after getting your e-mail and still nothing, no blue light. I have ordered a 4gb card so hopefully that will work, did everything in the installation procedure so maybe the fault lies with the card being 16gb.

**Comment by eduperez** [comment]
I was trying to make the video, and the procedure using EOScard was failing for me too: looks like the program tries to download a firmware, and when it fails leaves the card unprepared.

I could solve this by copying the files to the card first, and then executing EOScard: this way, the program detects the AUTOEXEC.BIN file, does not try to download a new copy, and prepares the card properly.

**Comment by Wizhunter** [comment]
So I should put AUTOEXEC.BIN File on the card before using eoscard, is that possible?. I am willing to try anything to get this working.
Thanks for helping, it's much appreciated.

**Comment by Wizhunter** [comment]
Just tried what i think you meant and its still not working :(

**Comment by eduperez** [comment]
What I did yesterday, on a Windows 10 box, and worked for me each time, was:
- Format the card in the camera.
- In the computer, copy AUTOEXEC.BIN to the card; you can also create a "400PLUS" folder in the card, and copy "LANGUAGES.INI" there.
- Launch EOScard as and administrator, check both "EOS_DEVELOP" and "BOOTDISK", and press "SAVE".
- Eject the card and insert it into the camera, switch the camera on, and then press the DP button to enter 400plus menu.

**Comment by Wizhunter** [comment]
It's now working and can I say a massive thanks for taking the time to help me.
You're a legend
Wizhunter

**Comment by eduperez** [comment]
Glad to know it works now! I updated the wiki page to make the procedure easier for others; thanks for your patience and kind words.
