### ISSUE TITLE
French translation update

### ISSUE THREAD

**Issue by ffvpor** [400plus/400plus#417]
# Initial Proposal
A new french.ini proposal to replace old 2011 version. It's in accordance with new_lang.ini 20160404-02 version.
It remains me 8 strings to translate (details below in french) !
@eduperez  I don't understand *Fl.* in named color temperatures. What's the corresponding word? Thanks to your help.
Because it's very specific, I keep developer menus in english. I did the same for *Safety Shift*.
@eduperez  A rebirth to my old 400D! Thank you very much.
## French reader
Une proposition d'un nouveau french.ini pour remplacer la version actuelle qui n'est plus en accord avec la version 20160404-02 du fichier new_lang.ini .
## Statut
Il reste 8 chaines à traduire (des idées ?):
  - 4 concernant le "bulb ramping". Je bloque sur la traduction de "ramping" et de "ramp";
  - 4 sur les températures de couleurs nommées : je ne comprends par l'abréviation Fl.
J'ai laissé dans l'état : ISO, Av, Tv, Jump, Trash et AEB. J'ai utilisé Ev comme synonyme d'exposition (*exposure*). Les menus specifiques développeur restent en anglais.

## Abréviations
  - Av : ouverture (*Aperture value*)
  - Tv : Vitesse (*Time value*)
  - Ev : Exposition (*Exposure value*)
  - Temp. : température(s)
  - auto. : automatique
  - sec. : seconde(s)
  - perso. : personalisé(s) pour traduire *custom*
  - aff. : afficheur
  - enr. : enregistrement
  - config. : configuration

**Comment by ffvpor** [comment]
With file, it's better ! Sorry

[french.txt](https://github.com/400plus/400plus/files/303117/french.txt)

**Comment by tibounise** [comment]
I think it's better to keep "Bulb ramping" in the french translation as the french Magic Lantern wiki doesn't translate it in french. Sometimes translations confuse people and it's better to keep the english expression.

I think "Fl." means "Fluorescent light" (tube néon) in that context.

**Comment by eduperez** [comment]
Changes look good to me, many thanks for your effort. I just committed the file to the main branch, but will wait a couple of days more before doing a new release, just to allow for some time to discuss the correct translation for "Bulb ramping".

**Comment by ffvpor** [comment]
# Release 1.0
All it's done (for now)!
[french-v1.0.txt](https://github.com/400plus/400plus/files/307551/french-v1.0.txt)
[diff-v0.9-v1.0.txt](https://github.com/400plus/400plus/files/307578/diff-v0.9-v1.0.txt)
@tibounise, thanks for your help

## Changes
- minor typographic corrections
- I keep Fl. in named color temperatures but translate colors
- About Bulb Ramping, no help on google nor qwant (the french google ). French writers use Bulb Ramping, Ramp size and Ramping thus I keep this english words

@eduperez 
When I tested my last translations, all strings are correct except V_NAMED_TEMP_3 to 6. They are translated in french.ini (and in my languages.ini test file) but in my 400D they remains in english. When I deleted 400plus configurations files (CMODES, PERSIST and SETTINGS), it was OK but I'm not sure if it was the best solution. Did I open a new issue ?

## Les changements effectués (french reader)
- Quelques corrections typographiques mineures;
- Les sites que j'ai consulté utilisent tous "*Bulb Ramping*" (souvent associé au "*timelapse*").  Pour l'instant, je conserve donc Ramping et Ramp size (Si un jour je trouve mieux, je ferais une nouvelle proposition !). Les valeurs entre parenthèses associées sont traduites. Pour rester cohérent, j'ai remis "Bulb ramping" dans S_BRAMP;
- Pour les températures nommées, j'ai traduit les couleurs. J'ai laissé Fl. comme lampe Fluorescente.

**Comment by eduperez** [comment]
I just merged the new version, thanks again for your efforts.

The V_NAMED_TEMP_x that you translated are used to give a default name to each entry, the first time the user enters the menu; then the settings are saved with whatever names the user might have edited. If you change the translation, changes will only have effect if the settings file is deleted.

**Comment by eduperez** [comment]
Released as 20160404-03; thanks.
