### ISSUE TITLE
doc: typo and clarification on install wiki

### ISSUE THREAD

**Issue by nicorikken** [400plus/400plus#422]
_I recently became the owner of a 400D, coming from Olympus MFT. Thanks to all contributers for creating such great software. Brings a lot of value to an otherwise pretty outdated body._

In the process of installing the custom firmware, I found a typo:
- [ ] In _Install 400plus into card_ the "additional (non-English) languages, **and** copy the" would better be replaced by "additional (non-English) languages, **also** copy the". Other solutions are also possible.

If the user has no super user rights, the `dd` command would error. Another option would be:
- [ ] `echo ... | sudo dd ...`

**bonus**
- [ ] Maybe the full wiki could be distributed as an `pdf` or `epub`, such that I would be able to read up on the functionalities on the road. Some hints on a related [Stackoverflow thread](http://stackoverflow.com/questions/18759738/effortless-export-from-github-wiki).

**Comment by tibounise** [comment]
Thank's for your contribution, the wiki has been edited. And epub/pdf version of the wiki should be doable, but I guess we have to do more work than just a pandoc conversion.
