### ISSUE TITLE
Firmware crash during P2P picture transfer on Linux using GPhoto2 via Darktable

### ISSUE THREAD

**Issue by nicorikken** [400plus/400plus#423]
Today experienced firmware crashes using a P2P image import. The half-filled 2GB CF-card worked fine. The fully filled 4GB CF-card gave errors. Both cards filled with high-quality L size JPEG images. This feature has worked before with a full card, although then it also contained a lot of RAW images.

**System**
Debian GNU/Linux testing (uname `4.6.0-1-amd64 #1 SMP Debian 4.6.4-1 (2016-07-18) x86_64 GNU/Linux`)
Darktable version 2.0.5
GPhoto2 version 2.5.10, libgphoto2 version 2.5.10, libgphoto2_port 0.12.0

**Issue**
1. Connect camera to running laptop, switch camera on.
2. Unmount file storage using Files (`nautilus`), to enable P2P
3. Open Darktable, (scan for devices, if needed), import from camera.
4. Dialog opens in Darktable, loading all images on the camera for a preview.
5. Whilst reading the images from the camera for preview (Red CF light on camera flashing constantly showing work in progress), a couple of hundred images in (I estimate) **the camera display freezes into a black-and-white repetitive pattern** (pattern is slightly different each time).
6. Turning the camera to the 'off' position is not sufficient, the battery will have to be remove to return into a usable state.

**Attempts to resolve**
* I tried to delete an image from the card via the camera to allow for some 'headroom', but that didn't work.
* I tried to get logging from `journalctl` but no details there.

**Potential causes**
* Maybe the number of files processed?
* Maybe the way Darktable loads the previews? (red CF-light on camera is flashing at a higher frequency than a file copy does.)
* Maybe the firmware influences the way GPhoto2 handles the file format?

**Workarounds (verified)**
* Transfer the images using a CF-card reader.
* Transfer the images using the mounted file storage.

_I'd be willing to do some more advanced debugging, but I would need some hints as to the way to debug._

**Comment by tibounise** [comment]
Do you get this issue without 400plus installed ?

**Comment by nicorikken** [comment]
Preventing 400PLUS from being loaded (trashcan on boot) does work. I just tested it. Darktable import fully supoorted (as was without 400PLUS). File based transfer with 400PLUS did actually fail on me today as well.

So issue remains, but best workaround seems to be, to prevent 400PLUS from being loaded at camera boot.

**Comment by eduperez** [comment]
Seems related to #421.

**Comment by eduperez** [comment]
After some tests, I can confirm this is definitively related to #421; we can close this issue, and continue the discussion there. Thanks!
