### ISSUE TITLE
1000D question

### ISSUE THREAD

**Issue by Sevrien** [400plus/400plus#444]
Hello,

I'm a complete newbee with an eos 1000D.
I'd like to give the 400plus a try.
But, it seems that the highest official canon release is 1.0.7 for a 1000D.
What are my options since the requested release is 1.1.1?

Greetings

**Comment by marssystems** [comment]
Hi!


This software is for the Canon 400 D only.


Best regards



________________________________

**Comment by Sevrien** [comment]
thanks for the reply,

so there are no options for the 1000D?

**Comment by eduperez** [comment]
No, I am afraid that there is currently no hack available for that camera.
