### ISSUE TITLE
install Release 20160404-09 SEE ReleaseCount 

### ISSUE THREAD

**Issue by xjhkai** [400plus/400plus#449]
install Release 20160404-09 SEE ReleaseCount

**Comment by eduperez** [comment]
Looks fine to me... what did you see? what did you expect to see?

**Comment by xjhkai** [comment]
Named color temps.  -- !f1. Day1ight   Look down Crash

**Comment by eduperez** [comment]
I guess there was no issue with the release counter after all...?
