### ISSUE TITLE
Shortcut "Flash on/off": Wrong display in main dialog

### ISSUE THREAD

**Issue by calle2010** [400plus/400plus#452]
Hi,

I use the shortcut "Flash on/off" (Main reason: I can still use the AF light on my flash, but it doesn't fire!) 

One issue with this:

- When in the 400plus flash menu "Disable flash" is set to "Yes" then
  - the flash is disabled (correct)
  - the shortcut shows "On" in the ISO field (bug)

- When in the 400plus flash menu "Disable flash" is set to "No" then
  - the flash is enabled (correct)
  - the shortcut shows "Off" in the ISO field (bug)

Moreover, the "2nd" indicator is only displayed when the flash is disabled, which makes no sense.

I think the issue is this line:
https://github.com/400plus/400plus/blob/7d6775d8154c2846c6d77ab48f442c0f10e2d68d/shortcuts.c#L363

I guess the variable name cf_emit_flash may be misleading and is ```true``` (or 1) when the flash is _disabled_?

PS: Many thanks for 400plus! I will use my 400D longer because of this extension.

**Comment by eduperez** [comment]
Yes, this is a bug!

**Comment by eduperez** [comment]
Fixed and released as 20160404-10.
Thanks for reporting this, thanks for your help fixing it, and thanks for your kind words.

**Comment by calle2010** [comment]
It works. Thank you very much for quick reaction.
