### ISSUE TITLE
400plus failing to install

### ISSUE THREAD

**Issue by jkugler** [400plus/400plus#454]
I followed the steps here: https://github.com/400plus/400plus/wiki/Firmware-Hack-Installation

I set the card to bootable via the method outlined (on Linux).

The camera has the 1.1.1 firmware. The camera boots, and there is no blue LED, and no 400plus menu.

The card was formatted by the camera.

Only (slight) possible hitch: I'm using an SD card in a SD to CF adapter. I don't know if that messes with the data transfer any.

Doing `sudo dd if=/dev/mmcblk0p1 bs=1 count=100` does verify the `EOS_DEVELOP` and `BOOTDISK` strings are present.

Any ideas?

**Comment by jeanthom** [comment]
Did you apply `testfir.fir`?

**Comment by jkugler** [comment]
Siiigh. PEBKBAC. Somehow my brain skipped that. Plus, 20160404-10 does that list that file. Will try that and report back. Thank you!

**Comment by eduperez** [comment]
I have tested `400plus` with a _Toshiba FlashAir Wireless Card_, inside a SD to CF adapter, and it worked perfectly.

As @jeanthom commented, remember to apply `testfir.fir` (or the camera will not even check the card), and copy the `AUTOEXEC.BIN` file to the card (that's `400plus`).

**Comment by jkugler** [comment]
Thank! I have a battery and charger on the way for this camera (second hand, no charger), so I'll wait to try until I have a fully charged battery. :)

**Comment by jkugler** [comment]
It all works! Thanks for your patiences, and sorry for the noise. :)
