### ISSUE TITLE
Can not boot up card (blue led doesn't turn on)

### ISSUE THREAD

**Issue by 1Mors** [400plus/400plus#457]
Hi, i tried installing 400Plus on my 400d, but the problem is, card does not seem bootable or the camera can not boot.
I followed the instructions on the tutorial page, but my camera doesn't turn on the print blue led once i turn it on, even tho the firmware has been updated to 1.1.1 and the camera ran testfir.fir.
I tried using 2 different CFs, a 2GB and an 8GB one, which eventually gave the same results... no blue led turning on. 
I tried making the cards bootables with 3 different files combination, with autoexec.bin on, with autoexec.bin and dcim and testfir.fir and blank, with zero results.
Can anyone please help me, because i'm starting to loose hope :(
Thanks to anyone who will respond.

**Comment by eduperez** [comment]
Did you follow all the instructions at "Make card bootable"? It is not enough to copy the files there, the card must also be tagged properly, or the camera will ignore the files.

**Comment by 1Mors** [comment]
What do you mean by tagged?

**Comment by eduperez** [comment]
See the instructions about EOS_DEVELOP and BOOTDISK; those are not files, but tags or labels, that mark the card as bootable for the camera.

**Comment by 1Mors** [comment]
I did what was requested, but the EOS_DEVELOP check tried to extract files from the ML zip, which I don't have, so I tried making the card bootable with the 400Plus files, as suggested, but still, it tried extracting from the ML zip.

**Comment by 1Mors** [comment]
@eduperez what do you suggest?

**Comment by eduperez** [comment]
Which OS and tool are you using?

**Comment by 1Mors** [comment]
Windows, and i used both recommend tools

**Comment by eduperez** [comment]
Try to do the full installation of Magic Lantern (zip file included), then remove all the files and folders from the card (but do not format it), and copy the AUTOEXEC.BIN file from 400plus.

**Comment by 1Mors** [comment]
Thanks, I'm going to try it.

**Comment by 1Mors** [comment]
@eduperez it now works, thanks for your help!
